(() => {
  const form=document.getElementById('courierQuoteForm');if(!form)return;
  const direction=form.elements.direction,country=form.elements.country,rows=document.getElementById('courierPackages');
  const result=document.getElementById('courierResult'),submit=document.getElementById('courierCalculate');
  const fields=document.getElementById('courierDetails'),manual=document.getElementById('courierManual');
  let options=null,revision=0,abort;
  const status=text=>{result.replaceChildren();result.hidden=false;const p=document.createElement('p');p.textContent=text;result.append(p);};
  function clear(){revision++;abort?.abort();result.hidden=true;result.replaceChildren();submit.disabled=!options;submit.textContent='Show my rates';}
  function packages(){return [...rows.children].map(row=>Object.fromEntries([...row.querySelectorAll('input')].map(el=>[el.dataset.key,Number(el.value)*(el.dataset.key==='weight'?(form.elements.weightUnit.value==='g'?.001:1):['length','width','height'].includes(el.dataset.key)?(form.elements.sizeUnit.value==='in'?2.54:1):1)])));}
  function add(){if(rows.children.length>=20)return;const row=document.createElement('div');row.className='cargo-package';
    row.innerHTML='<label>Pieces<input data-key="pieces" type="number" min="1" max="1000" step="1" value="1" required></label><label>Kg per piece<input data-key="weight" type="number" min="0.01" max="1000" step="0.01" required></label><label>Length (cm)<input data-key="length" type="number" min="0.1" max="1000" step="0.1" required></label><label>Width (cm)<input data-key="width" type="number" min="0.1" max="1000" step="0.1" required></label><label>Height (cm)<input data-key="height" type="number" min="0.1" max="1000" step="0.1" required></label><button type="button" class="cargo-tool" aria-label="Remove courier package group">Remove</button>';
    row.querySelector('button').addEventListener('click',()=>{row.remove();clear();removal();updateSummary();save();});rows.append(row);clear();removal();updateLabels();updateSummary();}
  function removal(){rows.querySelectorAll('button').forEach(b=>b.disabled=rows.children.length===1);document.getElementById('courierAddPackage').disabled=rows.children.length===20;}
  function countries(){const list=document.getElementById('courierCountries');list.replaceChildren();for(const c of options?.countries[direction.value]||[])list.append(new Option(c,c));document.getElementById('courierCountryLabel').textContent=(direction.value==='import'?'Origin':'Destination')+' country *';}
  direction.addEventListener('change',()=>{clear();const sea=direction.value==='sea';fields.hidden=sea;manual.hidden=!sea;fields.querySelectorAll('input,select,button').forEach(el=>el.disabled=sea);submit.hidden=sea;countries();if(!sea)removal();});
  form.addEventListener('input',clear);form.addEventListener('change',clear);
  document.getElementById('courierSeaEnquiry').addEventListener('click',()=>{const cargo=document.getElementById('cargoQuoteForm');cargo.elements.mode.value='sea';cargo.dispatchEvent(new Event('change'));});
  document.getElementById('courierAddPackage').addEventListener('click',()=>{add();rows.lastElementChild.querySelector('input').focus();save();});
  document.getElementById('courierReset').addEventListener('click',()=>{form.reset();for(const k of ["weightUnit","sizeUnit"])form.elements[k].dataset.previous=form.elements[k].value;form.elements.readyDate.value=today;rows.replaceChildren();add();direction.dispatchEvent(new Event('change'));try{sessionStorage.removeItem(storageKey);}catch{}document.getElementById('courierErrors').hidden=true;});
  form.addEventListener('submit',async event=>{event.preventDefault();if(direction.value==='sea'||!validate())return;
    clear();const version=revision;abort=new AbortController();submit.disabled=true;submit.textContent='Calculating…';status('Calculating your courier rates…');
    const input={direction:direction.value,country:country.value,readyDate:form.elements.readyDate.value,handling:form.elements.handling.value,packages:packages()};
    try {const data=await window.flexlyfCourierRequest('quote',input,abort.signal);
      if(version!==revision)return;result.replaceChildren();result.hidden=false;
      const title=document.createElement('h3');title.textContent=data.quotes.length?'Your courier estimates':'Let our team quote this shipment';result.append(title);
      if(data.shipment){const summary=document.createElement('p');summary.textContent=`${data.shipment.pieces} pieces · ${data.shipment.grossKg} kg actual · ${data.shipment.volumetricKg} kg volumetric · ${data.shipment.billableKg} kg estimated billable`;result.append(summary);}
      for(const [index,quote] of data.quotes.entries()){
        const card=document.createElement('article');card.className='courier-rate';
        const name=document.createElement('h4');name.textContent=quote.service;
        const price=document.createElement('strong');price.textContent=new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(quote.amount);
        const note=document.createElement('p');note.textContent=`${quote.chargedKg} kg rate slab · ${index===0?'Lowest available estimate':'Courier service'}`;
        const link=document.createElement('a');link.className='cargo-tool';link.textContent='Confirm this rate on WhatsApp';link.target='_blank';link.rel='noopener noreferrer';
        link.href='https://wa.me/919220819906?text='+encodeURIComponent(`Hello Flexlyf, please confirm courier estimate ${data.reference}: ${quote.service}, ${price.textContent}, ${input.direction==='export'?'India to '+input.country:input.country+' to India'}, ready ${input.readyDate}. Commodity: ${form.elements.commodity.value}. Packages: ${JSON.stringify(input.packages)}. Taxes and duties excluded. Please check postcode serviceability.`);
        card.append(name,price,note,link);result.append(card);
      }
      const note=document.createElement('p');note.className='cargo-note';note.textContent=data.message;result.append(note);
      const enquiry=document.createElement('a');enquiry.href='#cargo-quote';enquiry.textContent='Send shipment details for confirmation';enquiry.className='cargo-tool';enquiry.addEventListener('click',()=>{
        const cargo=document.getElementById('cargoQuoteForm');cargo.elements.mode.value=direction.value==='sea'?'sea':'air';cargo.elements.service.value='door-door';cargo.elements.commodity.value=form.elements.commodity.value;
        cargo.elements.readyDate.value=input.readyDate;cargo.elements.origin.value=input.direction==='export'?'India':input.country;cargo.elements.destination.value=input.direction==='export'?input.country:'India';
        cargo.elements.notes.value=`Courier estimate ${data.reference||'manual enquiry'}. Cargo type: ${input.handling}. Package details: ${JSON.stringify(input.packages)}. ${cargo.elements.notes.value}`.slice(0,2000);
        const cargoRows=document.getElementById('cargoPackages');
        cargo.dispatchEvent(new Event('change'));
        while(cargoRows.children.length<input.packages.length)document.getElementById('cargoAddPackage').click();
        while(cargoRows.children.length>input.packages.length)cargoRows.lastElementChild.querySelector('button').click();
        [...cargoRows.children].forEach((row,i)=>row.querySelectorAll('input').forEach(el=>el.value=input.packages[i][el.dataset.key]));
        cargo.dispatchEvent(new Event('change'));});result.append(enquiry);result.focus();
    }catch(error){if(error.name!=='AbortError'&&version===revision)status(error.message==='Failed to fetch'?'Rates could not be loaded. Please retry or use the manual enquiry form.':error.message);}
    finally{if(version===revision){submit.disabled=false;submit.textContent='Show my rates';}}
  });
  const storageKey='flexlyf-courier-draft-v1',today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});
  form.elements.readyDate.min=today;form.elements.readyDate.value=today;
  function updateLabels(){rows.querySelectorAll('input').forEach(el=>{const k=el.dataset.key;el.parentElement.firstChild.textContent=k==='pieces'?'Identical boxes *':k==='weight'?`Weight per box (${form.elements.weightUnit.value}) *`:`${k[0].toUpperCase()+k.slice(1)} (${form.elements.sizeUnit.value}) *`;el.inputMode=k==='pieces'?'numeric':'decimal';if(k!=='pieces'){el.step='any';el.max=k==='weight'&&form.elements.weightUnit.value==='g'?'1000000':k!=='weight'&&form.elements.sizeUnit.value==='in'?'393.700787':'1000';el.min='0.001';}});}
  function updateSummary(){const p=packages(),target=document.getElementById('courierLiveSummary');if(p.some(x=>Object.values(x).some(v=>!Number.isFinite(v)||v<=0))){target.textContent='Enter the weight and three dimensions of each box to see your shipping weight.';return;}let count=0,gross=0,billable=0;for(const x of p){count+=x.pieces;gross+=x.weight*x.pieces;const v=Math.ceil(x.length)*Math.ceil(x.width)*Math.ceil(x.height)/5000;billable+=Math.ceil((Math.max(x.weight,v)-1e-9)*2)/2*x.pieces;}target.textContent=`${count} boxes · ${Number(gross.toFixed(3))} kg actual · ${billable} kg estimated shipping weight`;}
  function save(){try{sessionStorage.setItem(storageKey,JSON.stringify({fields:Object.fromEntries(['direction','country','readyDate','commodity','handling','weightUnit','sizeUnit'].map(k=>[k,form.elements[k].value])),packages:[...rows.children].map(row=>Object.fromEntries([...row.querySelectorAll('input')].map(el=>[el.dataset.key,el.value])))}));}catch{}}
  function validate(){const errors=document.getElementById('courierErrors');errors.replaceChildren();const aliases={usa:'United States',us:'United States',uk:'United Kingdom',uae:'United Arab Emirates'};const typed=aliases[country.value.trim().toLowerCase()]||country.value.trim();const match=options?.countries[direction.value]?.find(c=>c.toLowerCase()===typed.toLowerCase());country.setCustomValidity(match?'':'Choose a country from the suggestions, or use the manual enquiry form for other routes.');if(match)country.value=match;const bad=[...form.querySelectorAll('input,select')].filter(el=>!el.disabled&&!el.checkValidity());form.querySelectorAll('[aria-invalid]').forEach(el=>el.removeAttribute('aria-invalid'));if(bad.length){const heading=document.createElement('strong');heading.textContent='Please check these details:';errors.append(heading);bad.forEach((el,i)=>{el.setAttribute('aria-invalid','true');el.id ||= `courier-field-${i}-${el.dataset.key||'detail'}`;const a=document.createElement('a');a.href='#'+el.id;a.textContent=`${el.closest('label')?.firstChild.textContent.trim()||'Shipment detail'}: ${el.validationMessage}`;a.addEventListener('click',e=>{e.preventDefault();el.focus();});errors.append(a);});errors.hidden=false;errors.focus();return false;}errors.hidden=true;return true;}
  country.addEventListener('input',()=>country.setCustomValidity(''));
  for(const [name,factor,keys] of [['weightUnit',1000,['weight']],['sizeUnit',2.54,['length','width','height']]]){form.elements[name].dataset.previous=form.elements[name].value;form.elements[name].addEventListener('change',()=>{const next=form.elements[name].value;if(next!==form.elements[name].dataset.previous){const multiplier=name==='weightUnit'?(next==='g'?factor:1/factor):(next==='cm'?factor:1/factor);rows.querySelectorAll('input').forEach(el=>{if(keys.includes(el.dataset.key)&&el.value)el.value=Number((Number(el.value)*multiplier).toFixed(6));});form.elements[name].dataset.previous=next;}updateLabels();updateSummary();save();});}
  form.addEventListener('input',()=>{updateSummary();save();});form.addEventListener('change',save);
  add();submit.disabled=true;
  try{const saved=JSON.parse(sessionStorage.getItem(storageKey));if(saved?.fields&&Array.isArray(saved.packages)&&saved.packages.length<=20&&saved.packages.length){for(const [k,v] of Object.entries(saved.fields))if(form.elements[k]){form.elements[k].value=v;if(k.endsWith("Unit"))form.elements[k].dataset.previous=v;}rows.replaceChildren();for(const p of saved.packages){add();rows.lastElementChild.querySelectorAll('input').forEach(el=>el.value=p[el.dataset.key]||'');}updateLabels();updateSummary();}}catch{}
  if(!window.FLEXLYF_COURIER_CONFIG?.endpoint&&!['localhost','127.0.0.1'].includes(location.hostname)) {status('Instant courier estimates are being connected. Please use the manual enquiry form below.');return;}
  window.flexlyfCourierRequest('options').then(data=>{options=data;direction.dispatchEvent(new Event('change'));submit.disabled=false;result.hidden=true;}).catch(()=>status('Instant rates are unavailable on this preview. Please use the manual enquiry form below.'));
})();
