(()=>{
  const body=document.getElementById('fxRows');if(!body)return;
  const status=document.getElementById('fxStatus'),search=document.getElementById('fxSearch'),select=document.getElementById('fxCurrency'),amount=document.getElementById('fxAmount'),output=document.getElementById('fxConverted'),refresh=document.getElementById('fxRefresh');
  let snapshot;
  const names=new Intl.DisplayNames(['en'],{type:'currency'}),money=new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:4});
  function convert(){const value=Number(amount.value);output.textContent=snapshot&&amount.value!==''&&Number.isFinite(value)&&value>=0&&value<=1e12?money.format(value*snapshot.rates[select.value].inr):'Enter a valid amount';}
  function render(){body.replaceChildren();const query=search.value.trim().toLowerCase();let found=0;for(const [code,rate] of Object.entries(snapshot.rates).sort(([a],[b])=>a.localeCompare(b))){const name=names.of(code);if(query&&!`${code} ${name}`.toLowerCase().includes(query))continue;const tr=document.createElement('tr');for(const text of [`${code} · ${name}`,money.format(rate.inr),rate.basis]){const td=document.createElement('td');td.textContent=text;tr.append(td);}body.append(tr);found++;}if(!found){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=3;td.textContent='No matching currency. Try a code such as USD.';tr.append(td);body.append(tr);}}
  async function load(){refresh.disabled=true;status.textContent='Checking published reference data…';try{const response=await fetch('data/fx-rates.json?t='+Date.now(),{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error();const data=await response.json();if(!/^\d{4}-\d{2}-\d{2}$/.test(data.date)||!data.rates?.USD||!Object.values(data.rates).every(x=>Number.isFinite(x.inr)&&x.inr>0))throw Error();snapshot=data;const age=(Date.now()-Date.parse(data.date+'T00:00:00Z'))/86400000;status.textContent=`Reference date: ${data.date} · Source: ECB · ${age>4?'Older data — verify with your bank before use.':'Latest available published snapshot; not live trading prices.'}`;const previous=select.value;select.replaceChildren();for(const code of Object.keys(data.rates).sort()){const option=document.createElement('option');option.value=code;option.textContent=code+' · '+names.of(code);select.append(option);}select.value=data.rates[previous]?previous:'USD';render();convert();}catch{status.textContent=snapshot?'Refresh failed. Previously displayed dated rates remain; verify with your bank.':'Currency data is unavailable. Please use the official source links below or contact our team.';}finally{refresh.disabled=false;}}
  search.addEventListener('input',()=>{if(snapshot)render();});amount.addEventListener('input',convert);select.addEventListener('change',convert);refresh.addEventListener('click',load);load();setInterval(()=>{if(!document.hidden)load();},15*60*1000);
})();
